site_name: LSCC Documentation
theme: flatly 
pages:
- 'Home': 'index.md'
- 'Tutorials':
  - 'Overview': 'tutorials/index.md'
  - 'NGS Overview': 'tutorials/ngs_overview/NGS_Overview.md'
  - 'Using Git and Github for revision control': 'tutorials/using_git/Using_Git.md'
  - 'Variant Detection Advanced': 'tutorials/var_detect_advanced/var_detect_advanced_background.md'
  - 'Introduction to Unix': 'tutorials/unix/index.md'
  - 'Python Overview': 'tutorials/python_overview/python_overview.md'
extra_templates: [
  'tutorials/unix/slides.html',
]
markdown_extensions: [
  'markdown_include.include',
  'showable',
]
